# Generated by Django 3.0.8 on 2020-11-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPLY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnum', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=7)),
                ('fraction', models.FloatField()),
                ('phone', models.CharField(max_length=12)),
                ('qq', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=18)),
                ('highschool', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '报名表',
                'verbose_name_plural': '报名表',
            },
        ),
        migrations.CreateModel(
            name='MSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('poster', models.URLField()),
                ('add_date', models.DateField()),
            ],
            options={
                'verbose_name': '咨讯新闻表',
                'verbose_name_plural': '咨讯新闻表',
            },
        ),
        migrations.CreateModel(
            name='QUES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesID', models.IntegerField()),
                ('quesTitle', models.CharField(default='None', max_length=17)),
                ('quesDetails', models.TextField()),
                ('quesLocation', models.CharField(default='上海市', max_length=10)),
                ('quesLikes', models.IntegerField(default=0)),
                ('recommond', models.IntegerField(default=0)),
                ('quesFloor', models.IntegerField()),
                ('quesSort', models.CharField(max_length=20)),
                ('quesDate', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(default='ECUST', max_length=20)),
                ('user_icon', models.URLField(default='https://www.ecustwxapp.com/media/img/login_logo.png')),
            ],
        ),
        migrations.CreateModel(
            name='SCHEDULE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=15)),
                ('num', models.IntegerField()),
                ('money', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '招生计划表',
                'verbose_name_plural': '招生计划表',
            },
        ),
        migrations.CreateModel(
            name='TEACHERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=10)),
                ('teacherID', models.CharField(max_length=8)),
                ('gender', models.CharField(default='None', max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=35)),
                ('subject', models.CharField(max_length=10)),
                ('wechatID', models.CharField(max_length=15)),
                ('academy', models.CharField(default='None', max_length=12)),
                ('position', models.CharField(max_length=6)),
                ('department', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': '老师权限申请表',
                'verbose_name_plural': '老师权限申请表',
            },
        ),
        migrations.CreateModel(
            name='WXUSER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('userID', models.IntegerField()),
                ('nickname', models.CharField(max_length=20)),
                ('province', models.CharField(default='上海', max_length=10)),
                ('user_icon', models.URLField(default='https://www.ecustwxapp.com/media/img/login_logo.png')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='ANS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_icon', models.URLField(default='https://www.ecustwxapp.com/media/img/login_logo.png')),
                ('ans_text', models.TextField(max_length=1999)),
                ('ansLikes', models.IntegerField(default=0)),
                ('ansFloor', models.IntegerField(default=-1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_ques', to='ECUSTapp.QUES')),
            ],
        ),
    ]
