# Generated by Django 3.0.8 on 2020-10-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECUSTapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='isDelete',
        ),
        migrations.AddField(
            model_name='ques',
            name='recommond',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.URLField(default='https://www.ecustwxapp.com/media/img/login_logo.png'),
        ),
        migrations.CreateModel(
            name='ANS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_icon', models.URLField(default='https://www.ecustwxapp.com/media/img/login_logo.png')),
                ('ans_text', models.TextField(max_length=1999)),
                ('ansLikes', models.IntegerField(default=0)),
                ('ansFloor', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECUSTapp.QUES')),
            ],
        ),
    ]
