# Generated by Django 3.0.8 on 2020-10-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECUSTapp', '0002_auto_20201008_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='username',
            field=models.CharField(default='ECUST', max_length=20),
        ),
    ]
