# Generated by Django 3.0.8 on 2020-10-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECUSTapp', '0003_ques_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='user_icon',
            field=models.URLField(default='https://www.ecustwxapp.com/media/img/login_logo.png'),
        ),
    ]
