# Generated by Django 3.0.8 on 2020-10-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECUSTapp', '0004_ques_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='quesTitle',
            field=models.CharField(default='None', max_length=17),
        ),
        migrations.AlterField(
            model_name='ques',
            name='quesLikes',
            field=models.IntegerField(default=0),
        ),
    ]
