# Generated by Django 3.0.8 on 2020-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECUSTapp', '0006_auto_20201014_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='quesLocation',
            field=models.CharField(default='上海市', max_length=10),
        ),
    ]
